name: meus_locais_app
description: A new Flutter project.
publish_to: 'none' 
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.1.4  
  google_maps_flutter: 2.0.6
  json_annotation: 4.0.1
  json_serializable: 4.1.3
  build_runner: 2.0.5
  flutter_cache_manager: 3.1.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  hive: 2.0.4
  hive_flutter: 1.1.0
  hive_generator: 1.1.0
  path_provider: 2.0.2
  fluttericon: 2.0.0
  geolocator: 7.2.0+1
  image_picker: 0.8.1+3
  validatorless: 1.2.0
  flutter_typeahead: 3.2.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/


